file:
  name: DSVol
  type: csv
  delimiter: ';'
  encoding: cp1251
fields:
  column0:
    name: AccountID
    from: id
  column1:
    name: Dsname
    from: companyName
  column2:
    name: Account
    from: accountNr
  column3:
    name: FIO
    from: fio
  column4:
    name: Curr_acc
    from: currAcc
  column5:
    name: INN
    from: inn
  column6:
    name: KPP
    from: kpp
  column7:
    name: OKATO
    from: okato
  column8:
    name: KBK
    from: kbk