dictionaries:
  DAT_PAYERS:
    format: dbf
    encoding: cp866
    main: yes
    fields:
      column1:
        name: op_dc_id
        type: integer
        changeable: no
      column2:
        name: op_pa_cnt
        type: string
        changeable: no
        key: ak1
      column3:
        name: op_pa_fio
        type: string
        changeable: yes
      column4:
        name: op_pa_adr
        type: string
        changeable: yes