file:
  name: GazpromChe
  type: csv
  delimiter: ';'
  encoding: cp1251
fields:
  column0:
    name: AccountID
    from: id
  column1:
    name: Account
    from: op_pa_cnt
  column2:
    name: Name
    from: op_pa_fio
  column3:
    name: Address
    from: op_pa_adr