file:
  name: Voda
  type: csv
  delimiter: ';'
  encoding: cp1251
fields:
  column0:
    name: AccountID
    from: id
  column1:
    name: Fio
    from: name
  column2:
    name: Address
    from: address
  column3:
    name: Account
    from: curr_acc
  column4:
    name: Debt_summ
    from: debt
  column5:
    name: ServiceID
    const: 998
  column6:
    name: Service
    const: 35313