file:
  name: Kommunalshik
  type: csv
  delimiter: ';'
  encoding: cp1251
fields:
  column0:
    name: AccountID
    from: id
  column1:
    name: Account
    from: accountNr
  column2:
    name: Name
    from: [lastName, firstName, secondName]
    delimiter: ' '
  column3:
    name: Address
    from: [cityName, streetName, houseNr, flatNr]
    delimiter: ', '
  column4:
    name: Debt_sum
    from: debtSum
  column5:
    name: Cold_water1
    from: coldWater1
  column6:
    name: Cold_water2
    from: coldWater2
  column7:
    name: Hot_water1
    from: hotWater1
  column8:
    name: Hot_water2
    from: hotWater2
  column9:
    name: Curr_acc
    from: currAcc