fryazinovo:
  filename: !ruby/regexp '/^S17734(\d\d)\.(\d\d\d)$/'
  filetype: zip
  type: clear

gazpromche:
  filename: !ruby/regexp '/^srg10(\d\d)(\d)\.(\d\d\d)$/'
  filetype: zip
  type: clear

gazpromvol:
  filename: !ruby/regexp '/^srg00(\d\d)(\d)\.(\d\d\d)$/'
  filetype: zip
  type: clear

kommunalshik:
  filename: !ruby/regexp '/^S14525(\d\d)\.(\d\d\d)$/'
  filetype: zip
  type: clear