fryazinovo:
  filename: !ruby/regexp '/^S17734(\d\d)\.(\d\d\d)$/'
  filetype: zip
  type: clear&insert

gazpromche:
  filename: !ruby/regexp '/^srg20(\d\d)(\d)\.(\d\d\d)$/'
  filetype: zip
  type: clear&insert