gazpromvol:
  filename: !ruby/regexp '/^(srg|SRG)(\d\d)(\d\d)(\d)\.(\d{1,3})$/'
  filetype: zip
  type: update

fryazinovo:
  filename: !ruby/regexp '/^S17734(\d\d)\.(\d{1,3})$/'
  filetype: zip
  type: clear

kommunalshik:
  filename: !ruby/regexp '/^S14525(\d\d)\.(\d{1,3})$/'
  filetype: zip
  type: clear

vas:
  filename: !ruby/regexp '/^S53353(\d\d)\.(\d{1,3})$/'
  filetype: zip
  type: clear

vasplus:
  filename: !ruby/regexp '/^S50232(\d\d)\.(\d{1,3})$/'
  filetype: zip
  type: clear

jss:
  filename: !ruby/regexp '/^S17162(\d{1,3})\.(\d{1,3})$/'
  filetype: zip
  type: update

uknt:
  filename: !ruby/regexp '/^S39080(\d\d)\.(\d{1,3})$/'
  filetype: zip
  type: update

uont:
  filename: !ruby/regexp '/^S40090(\d\d)\.(\d{1,3})$/'
  filetype: zip
  type: update

stm:
  filename: !ruby/regexp '/^S05120(\d\d)\.(\d{1,3})$/'
  filetype: zip
  type: update

stm1:
  filename: !ruby/regexp '/^S06850(\d\d)\.(\d{1,3})$/'
  filetype: zip
  type: update

souz:
  filename: !ruby/regexp '/^S17338(\d\d)\.(\d{1,3})$/'
  filetype: zip
  type: update

podshipnik:
  filename: !ruby/regexp '/^S15807(\d\d)\.(\d{1,3})$/'
  filetype: zip
  type: clear

cjs:
  filename: !ruby/regexp '/^S07210(\d\d)\.(\d{1,3})$/'
  filetype: zip
  type: update

vuk:
  filename: !ruby/regexp '/^S01091(\d\d)\.(\d{1,3})$/'
  filetype: zip
  type: clear

dsvol:
  filename: !ruby/regexp '/^S(DS)(\d\d\d)\.(\d{1,3})$/'
  filetype: zip
  type: update

vsc:
  filename: !ruby/regexp '/^S16958(\d\d)\.(\d{1,3})$/'
  filetype: text
  type: update

jeuk:
  filename: !ruby/regexp '/^S06780(\d\d)\.(\d{1,3})$/'
  filetype: zip
  type: clear

vposad:
  filename: !ruby/regexp '/^S\d{9}2\.(\d{1,3})$/'
  filetype: zip
  type: clear
  
byvalovo:
  filename: !ruby/regexp '/^S\d{9}1\.(\d{1,3})$/'
  filetype: zip
  type: clear

mkd:
  filename: !ruby/regexp '/^S12345\d{7}\.(\d{1,3})$/'
  filetype: text
  type: update
  
vodokanal:
  filename: !ruby/regexp '/^S16673(\d\d)(\d{5})\.(\d{1,3})$/'
  filetype: text
  type: update
  
vgts:
  filename: !ruby/regexp '/^S173160653(\d\d\d)\.(\d{1,3})$/'
  filetype: text
  type: update
  
visis:
  filename: !ruby/regexp '/^S15413(\d{1,3})\.(\d{1,3})$/'
  filetype: zip
  type: update
  
vselennaya:
  filename: !ruby/regexp '/^S51752(\d\d)\.(\d{1,3})$/'
  filetype: text
  type: update
  
ukvselennaya:
  filename: !ruby/regexp '/^S51752(\d\d\d)\.(\d{1,3})$/'
  filetype: text
  type: update
  
jkh:
  filename: !ruby/regexp '/^S\d{4}\.(\d{1,3})$/'
  filetype: zip
  type: clear