gazpromche:
  filename: !ruby/regexp '/^(srg|SRG)10(\d\d)(\d)\.(\d{1,3})$/'
  filetype: zip
  type: clear

gazpromvol:
  filename: !ruby/regexp '/^(srg|SRG)00(\d\d)(\d)\.(\d{1,3})$/'
  filetype: zip
  type: clear

fryazinovo:
  filename: !ruby/regexp '/^S17734(\d\d)\.(\d{1,3})$/'
  filetype: zip
  type: clear

kommunalshik:
  filename: !ruby/regexp '/^S14525(\d\d)\.(\d{1,3})$/'
  filetype: zip
  type: clear

vas:
  filename: !ruby/regexp '/^S53353(\d\d)\.(\d{1,3})$/'
  filetype: zip
  type: clear

vasplus:
  filename: !ruby/regexp '/^S50232(\d\d)\.(\d{1,3})$/'
  filetype: zip
  type: clear

jss:
  filename: !ruby/regexp '/^S15413(\d{1,3})\.(\d{1,3})$/'
  filetype: zip
  type: clear

uknt:
  filename: !ruby/regexp '/^S17162(\d\d)\.(\d{1,3})$/'
  filetype: zip
  type: clear

uknt:
  filename: !ruby/regexp '/^S05120(\d\d)\.(\d{1,3})$/'
  filetype: zip
  type: clear