fryazinovo:
  filename: !ruby/regexp '/^S17734(\d\d)\.(\d\d\d)$/'
  filetype: zip
  type: clear

gazpromche:
  filename: !ruby/regexp '/^(srg|SRG)10(\d\d)(\d)\.(\d\d\d)$/'
  filetype: zip
  type: clear

gazpromvol:
  filename: !ruby/regexp '/^(srg|SRG)00(\d\d)(\d)\.(\d\d\d)$/'
  filetype: zip
  type: clear

kommunalshik:
  filename: !ruby/regexp '/^S14525(\d\d)\.(\d\d\d)$/'
  filetype: zip
  type: clear

vas:
  filename: !ruby/regexp '/^S53353(\d\d)\.(\d\d\d)$/'
  filetype: zip
  type: clear

vasplus:
  filename: !ruby/regexp '/^S50232(\d\d)\.(\d\d\d)$/'
  filetype: zip
  type: clear