file:
  name: JEUK
  type: csv
  delimiter: ';'
  encoding: cp1251
fields:
  column0:
    name: AccountID
    from: id
  column1:
    name: Account
    from: accountNr
  column2:
    name: Name
    from: [lastName, firstName, secondName]
    delimiter: ' '
  column3:
    name: Address
    from: [cityName, streetName, houseNr, flatNr]
    delimiter: ', '
  column4:
    name: Debt_summ
    from: debtSum
    type: currency
  column5:
    name: Cold_water1
    from: coldWater1
    type: float
  column6:
    name: Cold_water2
    from: coldWater2
    type: float
  column7:
    name: Hot_water1
    from: hotWater1
    type: float
  column8:
    name: Hot_water2
    from: hotWater2
    type: float
  column9:
    name: Curr_acc
    from: currAcc
  column10:
    name: ServiceID
    from: currAcc
    replace: {971: 40702810612000103670}
