dictionaries:
  file:
      format: txt
      encoding: cp1251
      delimiter: 59
      main: yes
      startfrom: 5
      fields:
        column1:
          name: name
          type: string
          length: 0
          changeable: yes
        column2:
          name: address
          type: string
          changeable: yes
        column3:
          name: curr_acc
          type: string
          changeable: yes
        column4:
          name: debt
          type: string
          changeable: yes