dictionaries:
  file:
      format: txt
      encoding: cp1251
      delimiter: 59
      main: yes
      startfrom: 5
      header_def_symbol: #
      header:
        column1:
          name: FILESUM
          type: string
        column2:
          name: TYPE
          type: string
        column3:
          name: SERVICE
          type: integer
        column4:
          name: NOTE
          type: string
      fields:
        column1:
          name: name
          type: string
          length: 0
          changeable: yes
        column2:
          name: address
          type: string
          changeable: yes
        column3:
          name: curr_acc
          type: string
          changeable: yes
          key: ak1
        column4:
          name: debt
          type: string
          changeable: yes