dictionaries:
  abonent:
      format: txt
      encoding: cp866
      delimiter: 124
      main: yes
      fields:
        column1:
          name: companyID
          type: string
          length: 9
          changeable: no
          key: ak1
        column2:
          name: companyName
          type: string
          changeable: yes
        column3:
          name: inn
          type: string
          changeable: yes
        column4:
          name: kpp
          type: string
          changeable: yes
        column5:
          name: okato
          type: string
          changeable: yes
        column6:
          name: currAcc
          type: string
          changeable: yes
        column7:
          name: kbk
          type: string
          changeable: yes
        column8:
          name: FIO
          type: string
          changeable: yes
        column9:
          name: accountNr
          type: string
          length: 10
          changeable: no
          key: ak1