file:
  name: Example
  type: csv
  delimiter: ';'
  encoding: cp1251
fields:
  column0:
    name: AccountID
    from: id
  column1:
    name: Dscode
    from: companyID
  column2:
    name: Dsname
    from: inn
  column3:
    name: Ds
    from: companyName
  column4:
    name: Account
    from: accountNr
  column5:
    name: Fio
    from: FIO
  column6:
    name: Curr_acc
    from: currAcc
  column7:
    name: Inn
    from: inn
  column8:
    name: Kpp
    from: kpp
  column9:
    name: Okato
    from: okato
  column10:
    name: Kbk
    from: kbk
  column11:
    name: ServiceID
    const: 701